OUT = yaci
CC = cc
OBJ_DIR = obj
FLAGS = -std=c99 -Wall -Wextra -g -Werror `pkg-config --cflags readline libffi`
LIBS = -lm -lffi `pkg-config --libs readline libffi`
INCLUDES = -Isrc

SRC = $(wildcard src/*.c) src/lex.c src/parser.tab.c
OBJ = $(patsubst src/%.c,$(OBJ_DIR)/%.o,$(SRC)) obj/lex.o obj/parser.tab.o
HEADERS = $(wildcard src/*.h) 

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
	# macos thing
	FLAGS += -Wno-sign-compare 
endif

.PHONY: all clean package compile test cleanall

all: compile 

compile: $(OUT)

$(OUT): $(OBJ) 
	$(CC) $(FLAGS) $^ -o $@ $(LIBS)

$(OBJ_DIR)/%.o: src/%.c makefile $(HEADERS) src/parser.tab.h
	@mkdir -p $(dir $@)
	$(CC) $(FLAGS) $(INCLUDES) -c $< -o $@ 

src/lex.c: src/lex.l $(HEADERS) src/parser.tab.h
	flex -o src/lex.c src/lex.l 

src/parser.tab.c: src/parser.tab.h src/parser.y $(HEADERS) 
	@# generated by the same rule than src/parser.tab.h

src/parser.tab.h: src/parser.y $(HEADERS) 
	bison -bsrc/parser -d src/parser.y 

clean:
	rm -rf $(OBJ_DIR) test ./src/parser.tab.* ./src/lex.c

cleanall: clean
	cd ./misc-tests/ && make cleanall
	rm -rf $(OUT) $(OUT).zip 

test: 
	./tests/all.sh

docs: docs/yaci-es.pdf

docs/yaci-es.pdf: docs/yaci-es.typ
	cd docs/ && make

package: $(OUT).zip

$(OUT).zip: $(SRC) $(HEADERS) makefile README.md tests/* ./misc-tests/*
	zip $(OUT).zip $^ --update
