name: yaci tests
on: [push, pull_request]

jobs:
  macos:
    strategy:
    runs-on: macos-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          make CC=clang
          make test

  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          make CC=${{ matrix.cc }}
          make test
