name: yaci tests
on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          sudo apt install libreadline-dev
          make CC=${{ matrix.cc }}
          make test

  macos:
    strategy:
      matrix:
        cc: [clang]
    runs-on: macos-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          brew install readline
          make CC=${{ matrix.cc }}
          make test
